<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM9ti6le\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM9ti6le/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM9ti6le.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM9ti6le\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM9ti6le\appProdProjectContainer([
    'container.build_hash' => 'M9ti6le',
    'container.build_id' => '7ffd9bb9',
    'container.build_time' => 1645175872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM9ti6le');
